"""add proceeds + sec_type to execution facts view

Revision ID: c563484fc106
Revises: 13abadfe1737
Create Date: 2026-07-04 15:05:31.831265

Adds two columns to ``v_execution_facts`` so the semantic layer can answer
cash-flow / premium questions (premium collected vs paid — e.g. covered-call
financing) without depending on the ``contracts`` security master, which is
incomplete for many traded option ``con_id``s:

  - ``proceeds`` — IBKR FlexQuery signed gross cash for the fill (SELL positive =
    cash in / premium collected; BUY negative = cash out / premium paid). This is
    ``price x multiplier x qty`` already computed and signed by IBKR, so we do NOT
    reconstruct it (avoids price-magnifier / multiplier pitfalls). Combo-safe:
    NULL on synthetic ``combo_summary`` rows, exactly like ``realized_pnl``.
  - ``sec_type`` — the instrument type straight off ``trade_executions`` (STK,
    FUT, OPT, FOP), so premium can be split stock-vs-options at the fact grain
    without joining ``contracts``.

Recreated with CREATE OR REPLACE VIEW appending columns at the end; existing
columns are unchanged so the dependent ``v_trade_facts`` view is unaffected.
Read-only view change — no data migration or backfill.

NOTE: generated with ``task migrate:new`` (auto-assigned revision/down_revision
preserved); the autogenerated body (unrelated index/FK drift) was replaced with
the view DDL below.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c563484fc106"
down_revision: Union[str, Sequence[str], None] = "13abadfe1737"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Current view (adds proceeds + sec_type at the end).
_NEW = """
CREATE OR REPLACE VIEW v_execution_facts AS
SELECT
    te.id          AS execution_id,
    te.trade_id    AS trade_id,
    te.account_id  AS account_id,
    te.con_id      AS con_id,
    te.exec_role   AS exec_role,
    te.executed_at AS executed_at,
    te.quantity    AS quantity,
    te.price       AS price,
    te.commission  AS commission,
    CASE
        WHEN te.exec_role <> 'combo_summary'
        THEN NULLIF(te.raw ->> 'fifoPnlRealized', '')::numeric
    END AS realized_pnl,
    CASE
        WHEN te.exec_role <> 'combo_summary'
        THEN NULLIF(te.raw ->> 'proceeds', '')::numeric
    END AS proceeds,
    te.sec_type    AS sec_type
FROM trade_executions te
WHERE te.is_canonical
"""

# Prior view (without proceeds / sec_type), recreated on downgrade.
_OLD = """
CREATE OR REPLACE VIEW v_execution_facts AS
SELECT
    te.id          AS execution_id,
    te.trade_id    AS trade_id,
    te.account_id  AS account_id,
    te.con_id      AS con_id,
    te.exec_role   AS exec_role,
    te.executed_at AS executed_at,
    te.quantity    AS quantity,
    te.price       AS price,
    te.commission  AS commission,
    CASE
        WHEN te.exec_role <> 'combo_summary'
        THEN NULLIF(te.raw ->> 'fifoPnlRealized', '')::numeric
    END AS realized_pnl
FROM trade_executions te
WHERE te.is_canonical
"""


def upgrade() -> None:
    op.execute(_NEW)


def downgrade() -> None:
    # CREATE OR REPLACE can't drop columns; drop + recreate the prior shape.
    # v_trade_facts depends on this view but only on unchanged columns, so it
    # need not be rebuilt — but the drop requires removing the dependency first.
    op.execute("DROP VIEW IF EXISTS v_trade_facts")
    op.execute("DROP VIEW IF EXISTS v_execution_facts")
    op.execute(_OLD)
    op.execute("""
        CREATE VIEW v_trade_facts AS
        SELECT
            t.id               AS trade_id,
            t.account_id       AS account_id,
            t.symbol           AS symbol,
            t.sec_type         AS sec_type,
            t.side             AS side,
            t.status           AS status,
            t.last_executed_at AS last_executed_at,
            SUM(ef.realized_pnl) AS realized_pnl
        FROM trades t
        LEFT JOIN v_execution_facts ef ON ef.trade_id = t.id
        GROUP BY t.id, t.account_id, t.symbol, t.sec_type, t.side, t.status, t.last_executed_at
        """)
