"""semantic position facts view

Revision ID: 13abadfe1737
Revises: 0a388cb95eb0
Create Date: 2026-07-04 14:56:26.992705

Adds `v_position_facts` — the open-position fact source for the semantic layer
(see docs/core/semantic-queries.md and docs/core/semantic-data-model.md).

One row per *open* position (``positions.position <> 0``). Additive measures
(net quantity, market value, unrealized PnL) and an ``open_position_count`` live
here. The contract's expiration (``positions.last_trade_date``, an IBKR
``YYYYMMDD``-style ``YYYY-MM-DD`` string, NULL for stock) is cast to a real
``date`` column ``expiration`` so the resolver can range-filter it as a time
dimension and derive days-to-expiration at query time.

Read-only view over the existing ``positions`` table — no columns, data
migration, or backfill. Account is a join to ``accounts`` at query time (the
human alias), not baked into the view.

NOTE: this file was generated with ``task migrate:new`` (auto-assigned
revision/down_revision preserved); the autogenerated body — incidental
index/FK drift unrelated to this change — was replaced with the view DDL below.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13abadfe1737"
down_revision: Union[str, Sequence[str], None] = "0a388cb95eb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_POSITION_FACTS = """
CREATE VIEW v_position_facts AS
SELECT
    p.id                                AS position_id,
    p.account_id                        AS account_id,
    p.con_id                            AS con_id,
    p.symbol                            AS symbol,
    p.sec_type                          AS sec_type,
    p."right"                           AS "right",
    p.strike                            AS strike,
    NULLIF(p.last_trade_date, '')::date AS expiration,
    p.position                          AS quantity,
    p.avg_cost                          AS avg_cost,
    p.mark_price                        AS mark_price,
    p.position_value                    AS position_value,
    p.fifo_pnl_unrealized               AS unrealized_pnl
FROM positions p
WHERE p.position <> 0
"""


def upgrade() -> None:
    op.execute(_POSITION_FACTS)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_position_facts")
