"""position trade group bridge view

Revision ID: 936d0e0f325f
Revises: c563484fc106
Create Date: 2026-07-04 21:41:34.241514

Adds ``v_position_trade_group`` — a DISTINCT bridge mapping each position
(``account_id``, ``con_id``) to every trade group whose executions touched it.
This lets the semantic layer expose **settled unrealized PnL by trade group**
(``tag``) over ``v_position_facts`` (see docs/core/semantic-data-model.md).

The bridge is DISTINCT on (trade_group_id, account_id, con_id), so joining
``v_position_facts`` → bridge → ``trade_groups`` does not fan out a position's
additive measures *within a single group*. It is intentionally many-to-many
across groups: a position shared by two groups is attributed to both, so
settled-unrealized summed with NO tag filter double-counts shared positions.
This matches the attribution of the ``trade_group_pnl`` tool exactly — query one
group at a time. Intraday/live unrealized stays in that tool (a read-time TWS
overlay, not expressible in SQL).

Read-only view over existing tables — no data migration or backfill.

NOTE: generated with ``task migrate:new`` (auto-assigned revision/down_revision
preserved); the autogenerated body (unrelated index/FK drift) was replaced with
the view DDL below.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "936d0e0f325f"
down_revision: Union[str, Sequence[str], None] = "c563484fc106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_BRIDGE = """
CREATE VIEW v_position_trade_group AS
SELECT DISTINCT
    tge.trade_group_id AS trade_group_id,
    te.account_id      AS account_id,
    te.con_id          AS con_id
FROM trade_group_executions tge
JOIN trade_executions te ON te.id = tge.trade_execution_id
WHERE te.con_id IS NOT NULL
"""


def upgrade() -> None:
    op.execute(_BRIDGE)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_position_trade_group")
