"""add intraday overlay tables

Revision ID: 3b28da5d71f9
Revises: 19412730c878
Create Date: 2026-06-20 18:51:03.125117

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b28da5d71f9"
down_revision: Union[str, Sequence[str], None] = "19412730c878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "latest_quote",
        sa.Column("con_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.Column("last", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("mark", sa.Float(), nullable=True),
        sa.Column("market_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("con_id"),
    )
    op.create_table(
        "live_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ib_exec_id", sa.Text(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("con_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("sec_type", sa.String(), nullable=True),
        sa.Column("local_symbol", sa.String(), nullable=True),
        sa.Column("multiplier", sa.String(), nullable=True),
        sa.Column("right", sa.String(), nullable=True),
        sa.Column("strike", sa.Float(), nullable=True),
        sa.Column("side", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("exec_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ib_exec_id"),
    )
    op.create_index("ix_live_executions_account_id_con_id", "live_executions", ["account_id", "con_id"], unique=False)
    op.create_table(
        "live_positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("con_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("sec_type", sa.String(), nullable=True),
        sa.Column("local_symbol", sa.String(), nullable=True),
        sa.Column("multiplier", sa.String(), nullable=True),
        sa.Column("right", sa.String(), nullable=True),
        sa.Column("strike", sa.Float(), nullable=True),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("avg_cost", sa.Float(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "con_id", name="uq_live_positions_account_id_con_id"),
    )
    # NOTE: autogenerate also flagged unrelated drops of pre-existing indexes /
    # FK churn (jobs, trades, trade_executions, tag_links, etc.) that reflect
    # drift between the live DB and the models, not this change. Those were
    # intentionally removed so this migration only adds the three overlay tables.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("live_positions")
    op.drop_index("ix_live_executions_account_id_con_id", table_name="live_executions")
    op.drop_table("live_executions")
    op.drop_table("latest_quote")
