#!/usr/bin/env python3
"""Generate README.md files for docs/ and every docs subdirectory.

For each directory under docs/ that contains .md files, writes a README.md
(auto-rendered by GitHub) listing the .md files in that directory (not
recursive) with their front-matter `description` (empty when absent). Every
README also links to subdirectory READMEs at the top.

docs/core/ is indexed here too (it previously had its own generator).

Overwrites existing README.md files; never lists README.md itself.

Usage:
    uv run python scripts/docs_index.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

FRONT_MATTER_RE = re.compile(r"^---\n(.*?)^---", re.DOTALL | re.MULTILINE)
KEY_VALUE_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$")

GENERATED_BANNER = "<!-- Generated by scripts/docs_index.py (do not edit) -->"


def parse_field(path: Path, key: str) -> str:
    """Return a front-matter scalar value, or empty string if absent.

    Only simple single-line `key: value` entries are read (flow-style lists
    are returned verbatim); anything else yields "".
    """
    m = FRONT_MATTER_RE.match(path.read_text(encoding="utf-8"))
    if not m:
        return ""
    for line in m.group(1).splitlines():
        kv = KEY_VALUE_RE.match(line.strip())
        if kv and kv.group(1) == key:
            return kv.group(2).strip().strip("\"'")
    return ""


def parse_topics(path: Path) -> str:
    """Front-matter `topics` as a comma-separated string, or ""."""
    raw = parse_field(path, "topics")
    if not raw:
        return ""
    items = [t.strip(" \"'[]") for t in raw.split(",") if t.strip(" \"'[]")]
    return ", ".join(items)


def md_files(directory: Path) -> list[Path]:
    """Non-index .md files directly in this directory."""
    return sorted(p for p in directory.glob("*.md") if p.name not in ("README.md", "_index.md"))


def doc_subdirs(directory: Path) -> list[Path]:
    """Immediate subdirectories that contain (at any depth) .md files."""
    return sorted(d for d in directory.iterdir() if d.is_dir() and any(d.rglob("*.md")))


def render_index(title: str, subdirs: list[Path], files: list[Path]) -> str:
    lines = [f"# {title}", "", GENERATED_BANNER, ""]
    if subdirs:
        lines += ["## Directories", "", "| Directory | Index |", "| --- | --- |"]
        for d in subdirs:
            lines.append(f"| `{d.name}/` | [README.md]({d.name}/README.md) |")
        lines.append("")
    lines += ["## Files", "", "| Doc | Topics | Description |", "| --- | --- | --- |"]
    for f in files:
        topics = parse_topics(f)
        desc = parse_field(f, "description")
        lines.append(f"| [{f.name}]({f.name}) | {topics} | {desc} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    if not DOCS.is_dir():
        raise SystemExit(f"docs dir not found: {DOCS}")

    # Every directory under docs/ that has .md files anywhere beneath it,
    # so intermediate containers (e.g. solutions/) get indexes too.
    dirs = [d for d in [DOCS, *DOCS.rglob("*")] if d.is_dir() and any(d.rglob("*.md"))]
    for d in dirs:
        files = md_files(d)
        title = "Docs Index" if d == DOCS else f"{d.name}/ Index"
        (d / "README.md").write_text(render_index(title, doc_subdirs(d), files), encoding="utf-8")
        print(f"Wrote {d / 'README.md'} ({len(files)} file(s))")


if __name__ == "__main__":
    main()
