#!/usr/bin/env python3
"""Generate docs/core/README.md — a table of core docs and their front matter.

Reads every .md file in docs/core/, parses YAML front matter, and writes a
README.md (auto-rendered by GitHub) with a table: file, topics,
code_dirs_or_files, description.

Overwrites docs/core/README.md; never lists README.md itself.

Usage:
    uv run python scripts/gen_core_index_html.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = ROOT / "docs" / "core"
OUTPUT = CORE_DIR / "README.md"

FRONT_MATTER_RE = re.compile(r"^---\n(.*?)^---", re.DOTALL | re.MULTILINE)

GENERATED_BANNER = "<!-- Generated by scripts/gen_core_index_html.py (do not edit) -->"


def parse_front_matter(path: Path) -> dict[str, str] | None:
    """Extract front matter as a dict, or None if absent."""
    text = path.read_text(encoding="utf-8")
    m = FRONT_MATTER_RE.match(text)
    if not m:
        return None
    raw = m.group(1)
    result: dict[str, str] = {}
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        # Strip YAML list brackets and quotes: ["a", "b"] -> a, b
        if value.startswith("[") and value.endswith("]"):
            value = value[1:-1]
            value = re.sub(r'["\s]', "", value)
            value = value.replace(",", ", ")
        elif value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        result[key] = value
    return result


def render_markdown(rows: list[tuple[str, dict[str, str]]]) -> str:
    """Render the README.md table."""
    lines = [
        "# Core Docs",
        "",
        GENERATED_BANNER,
        "",
        f"{len(rows)} doc(s).",
        "",
        "| Doc | Topics | Code dirs / files | Description |",
        "| --- | --- | --- | --- |",
    ]
    for file_rel, fm in rows:
        topics = fm.get("topics", "—")
        code_dirs = fm.get("code_dirs_or_files", "—")
        desc = fm.get("description", "—")
        name = Path(file_rel).name
        lines.append(f"| [{name}]({name}) | {topics} | {code_dirs} | {desc} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    if not CORE_DIR.is_dir():
        print(f"Error: {CORE_DIR} is not a directory", file=sys.stderr)
        sys.exit(1)

    md_files = sorted(CORE_DIR.glob("*.md"))
    if not md_files:
        print("No .md files found in docs/core/", file=sys.stderr)
        sys.exit(1)

    rows: list[tuple[str, dict[str, str]]] = []
    for f in md_files:
        if f.name == "README.md":
            continue
        fm = parse_front_matter(f)
        rel = str(f.relative_to(ROOT))
        if fm is None:
            print(f"  ⚠ {rel}: no front matter — skipped", file=sys.stderr)
            continue
        rows.append((rel, fm))

    if not rows:
        print("No files with front matter found", file=sys.stderr)
        sys.exit(1)

    OUTPUT.write_text(render_markdown(rows), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(rows)} row(s))")


if __name__ == "__main__":
    main()
